# Generated by Django 4.2 on 2026-04-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
