# Generated by Django 4.2.29 on 2026-05-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
