# Generated by Django 4.2.29 on 2026-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
