# Generated by Django 4.2 on 2026-05-01 20:42

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
