# Generated by Django 4.2.29 on 2026-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movielist_movielistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='movielist',
            constraint=models.UniqueConstraint(condition=models.Q(('list_type__in', ['favorites', 'must_watch'])), fields=('user', 'list_type'), name='unique_default_lists_per_user'),
        ),
    ]
