# Generated by Django 4.2 on 2026-05-01 21:06

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_description_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
