# Generated by Django 4.2.29 on 2026-05-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_watchlist_watched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
    ]
