# Generated by Django 4.2 on 2026-05-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_description_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
