# Generated by Django 4.2.29 on 2026-05-06 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_watchlist_delete_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watched',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
