# Generated by Django 4.2 on 2026-05-01 20:42

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_watched_movie'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # skip — column already exists
            state_operations=[
                migrations.AddField(
                    model_name='movie',
                    name='description_vector',
                    field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
                ),
            ]
        )
    ]
